// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as More from "./More.bs.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Other from "./Other.bs.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

import things from 'hello'
;

import moreThings from 'other'
;

var x = {
  a: 3
};

var l = (More.outer + More.n | 0) + Other.inner | 0;

var me = /* People */Block.__(1, ["Hie"]);

var x$1 = Other.something + 10 | 0;

var Something_000 = /* m : record */[
  /* name */"Me",
  /* age */0
];

var Something_001 = /* animal : Things */Block.__(0, [10]);

var Something_002 = /* other : Things */Block.__(0, [2]);

var Something = /* module */[
  Something_000,
  Something_001,
  Something_002,
  /* me */me,
  /* x */x$1,
  /* r */"Me",
  /* awesome */20
];

if (typeof me !== "number") {
  !me.tag;
}

var aThing = 10 + Other.something | 0;

function transform(x, y) {
  return x + Pervasives.string_of_float(y);
}

"hello " + Pervasives.string_of_float(5);

var added = 110;

var a_001 = /* :: */[
  "my finefolks",
  /* :: */[
    "in boonville",
    /* [] */0
  ]
];

var a = /* :: */[
  "hello",
  a_001
];

function div(_, _$1, _$2, _$3) {
  return 10;
}

function something() {
  return /* () */0;
}

function someFunction(memorableName, _) {
  return memorableName + 20 | 0;
}

for(var _index = 0; _index <= 10; ++_index){
  console.log("hellO");
}

var TwoTwoTwoTwo = /* module */[/* xxxxxxxxxx */10];

var OneOneOneOne = /* module */[/* TwoTwoTwoTwo */TwoTwoTwoTwo];

var y = 15;

var z = /* record */[/* contents */30];

function thing() {
  return 77;
}

var contents = z[/* contents */0];

var someLongName = 10;

var otherLongName = "string";

var zzz = 1;

var more = 20;

var m = Other.later;

var r = 10;

var xxxxxxxxxx = 10;

var contnets = More.contnets;

var outer = More.outer;

var n = More.n;

var party = /* record */[
  /* one */"one",
  /* two */2
];

var one = "one";

var two = 2;

var awesome = "hello";

export {
  someLongName ,
  otherLongName ,
  x ,
  l ,
  Something ,
  aThing ,
  transform ,
  zzz ,
  more ,
  added ,
  a ,
  div ,
  something ,
  someFunction ,
  m ,
  OneOneOneOne ,
  r ,
  xxxxxxxxxx ,
  contnets ,
  outer ,
  n ,
  y ,
  z ,
  party ,
  one ,
  two ,
  thing ,
  contents ,
  awesome ,
  
}
/*  Not a pure module */
