// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE


var contnets = "here";

var outer = 20;

var n = 10;

var party = 30;

export {
  contnets ,
  outer ,
  n ,
  party ,
  
}
/* No side effect */
