// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";

var z = /* record */[
  /* name */"hi",
  /* age */20
];

function concat(first, second) {
  return first + second | 0;
}

var oo = /* record */[
  /* person */z,
  /* height */34.2
];

function show() {
  return /* () */0;
}

var something = 10;

var inner = 10;

var m = /* Things */Block.__(0, [1]);

var later = 20;

export {
  something ,
  inner ,
  m ,
  z ,
  later ,
  concat ,
  oo ,
  show ,
  
}
/* No side effect */
