// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Emotion = require("@ahrefs/bs-emotion/src/Emotion.bs.js");

var container = Emotion.css(undefined, /* :: */[
      Emotion.label("container"),
      /* :: */[
        Emotion.display(/* flex */-1010954439),
        /* :: */[
          Emotion.flexFlow(/* column */-963948842, /* nowrap */867913355),
          /* :: */[
            Emotion.alignItems(/* center */98248149),
            /* [] */0
          ]
        ]
      ]
    ]);

var shape = Emotion.css(undefined, /* :: */[
      Emotion.label("shape"),
      /* :: */[
        Emotion.display(/* flex */-1010954439),
        /* :: */[
          Emotion.flexFlow(/* row */5693978, /* nowrap */867913355),
          /* :: */[
            Emotion.alignItems(/* center */98248149),
            /* :: */[
              Emotion.justifyContent(/* center */98248149),
              /* :: */[
                Emotion.transitionProperty("border-radius"),
                /* :: */[
                  Emotion.transitionDuration(/* `ms */[
                        24422,
                        100
                      ]),
                  /* :: */[
                    Emotion.transitionTimingFunction(/* easeInOut */-960651557),
                    /* :: */[
                      Emotion.width(/* `px */[
                            25096,
                            200
                          ]),
                      /* :: */[
                        Emotion.height(/* `px */[
                              25096,
                              200
                            ]),
                        /* :: */[
                          Emotion.borderRadius(/* `px */[
                                25096,
                                6
                              ]),
                          /* :: */[
                            Emotion.backgroundColor(/* `hex */[
                                  5194459,
                                  "29d"
                                ]),
                            /* :: */[
                              Emotion.hover(/* :: */[
                                    Emotion.borderRadius(/* `pct */[
                                          5591841,
                                          50
                                        ]),
                                    /* :: */[
                                      Emotion.important(Emotion.cursor(/* grab */-999567412)),
                                      /* [] */0
                                    ]
                                  ]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

function text(size) {
  return Emotion.css(undefined, /* :: */[
              Emotion.label("text"),
              /* :: */[
                Emotion.color(/* `hex */[
                      5194459,
                      "fff"
                    ]),
                /* :: */[
                  Emotion.fontSize(/* `px */[
                        25096,
                        size
                      ]),
                  /* :: */[
                    Emotion.fontWeight(700),
                    /* :: */[
                      Emotion.transition("font-size", /* `ms */[
                            24422,
                            100
                          ], /* easeInOut */-960651557, /* zero */-789508312),
                      /* :: */[
                        Emotion.transitions(/* :: */[
                              /* tuple */[
                                "font-size",
                                /* `ms */[
                                  24422,
                                  100
                                ],
                                /* easeInOut */-960651557,
                                /* `ms */[
                                  24422,
                                  0
                                ]
                              ],
                              /* [] */0
                            ]),
                        /* :: */[
                          Emotion.select("." + (String(container) + ":hover &"), /* :: */[
                                Emotion.fontSize(Curry._2(Emotion.Css.Calc.$star, Curry._2(Emotion.Css.Calc.$plus, /* `px */[
                                              25096,
                                              size
                                            ], /* `pct */[
                                              5591841,
                                              150
                                            ]), /* `n */[
                                          110,
                                          1.5
                                        ])),
                                /* [] */0
                              ]),
                          /* :: */[
                            Emotion.media("(max-width: 900px)", /* :: */[
                                  Emotion.color(/* `hex */[
                                        5194459,
                                        "ff69b4"
                                      ]),
                                  /* :: */[
                                    Emotion.select(":hover", /* :: */[
                                          Emotion.color(/* `hex */[
                                                5194459,
                                                "fff"
                                              ]),
                                          /* [] */0
                                        ]),
                                    /* [] */0
                                  ]
                                ]),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var bounce = Emotion.keyframes(/* :: */[
      /* tuple */[
        0,
        /* :: */[
          Emotion.transform(/* `translateY */[
                106728779,
                /* zero */-789508312
              ]),
          /* [] */0
        ]
      ],
      /* :: */[
        /* tuple */[
          50,
          /* :: */[
            Emotion.transform(/* `translateY */[
                  106728779,
                  /* `px */[
                    25096,
                    -20
                  ]
                ]),
            /* [] */0
          ]
        ],
        /* :: */[
          /* tuple */[
            100,
            /* :: */[
              Emotion.transform(/* `translateY */[
                    106728779,
                    /* zero */-789508312
                  ]),
              /* [] */0
            ]
          ],
          /* [] */0
        ]
      ]
    ]);

var animated = Emotion.css(undefined, /* :: */[
      Emotion.label("animated"),
      /* :: */[
        Emotion.animationName(bounce),
        /* :: */[
          Emotion.animationDuration(/* `ms */[
                24422,
                300
              ]),
          /* :: */[
            Emotion.animationIterationCount(/* `i */[
                  105,
                  7
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var smallText = Emotion.css(undefined, /* :: */[
      Emotion.label("smallText"),
      /* :: */[
        Emotion.fontSize(/* `em */[
              22632,
              0.8
            ]),
        /* [] */0
      ]
    ]);

var note = Emotion.css(smallText, /* :: */[
      Emotion.label("note"),
      /* :: */[
        Emotion.margin2(/* `px */[
              25096,
              20
            ], /* zero */-789508312),
        /* [] */0
      ]
    ]);

var grid = Emotion.css(undefined, /* :: */[
      Emotion.label("grid"),
      /* :: */[
        Emotion.display(/* grid */-999565626),
        /* :: */[
          Emotion.gridTemplateColumns(/* `list */[
                -944563106,
                /* :: */[
                  /* `repeat */[
                    108828507,
                    /* tuple */[
                      /* `n */[
                        110,
                        3
                      ],
                      /* :: */[
                        /* `px */[
                          25096,
                          100
                        ],
                        /* [] */0
                      ]
                    ]
                  ],
                  /* [] */0
                ]
              ]),
          /* :: */[
            Emotion.gridAutoRows(/* `px */[
                  25096,
                  100
                ]),
            /* :: */[
              Emotion.gridGap(/* `px */[
                    25096,
                    10
                  ]),
              /* :: */[
                Emotion.gridTemplateAreas(/* `areas */[
                      629510214,
                      /* :: */[
                        "a a a",
                        /* :: */[
                          ". . .",
                          /* :: */[
                            ". . .",
                            /* [] */0
                          ]
                        ]
                      ]
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var gridItem = Emotion.css(undefined, /* :: */[
      Emotion.label("gridItem"),
      /* :: */[
        Emotion.padding(/* `px */[
              25096,
              10
            ]),
        /* :: */[
          Emotion.color(/* `hex */[
                5194459,
                "fff"
              ]),
          /* :: */[
            Emotion.backgroundColor(/* `hex */[
                  5194459,
                  "29d"
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var gridItem1 = Emotion.css(undefined, /* :: */[
      Emotion.label("gridItem1"),
      /* :: */[
        Emotion.gridArea("a"),
        /* [] */0
      ]
    ]);

exports.container = container;
exports.shape = shape;
exports.text = text;
exports.bounce = bounce;
exports.animated = animated;
exports.smallText = smallText;
exports.note = note;
exports.grid = grid;
exports.gridItem = gridItem;
exports.gridItem1 = gridItem1;
/* container Not a pure module */
