// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("@ahrefs/bs-emotion/src/Emotion.bs.js");

Emotion.$$global("html", /* :: */[
      Emotion.minHeight(/* `pct */[
            5591841,
            100
          ]),
      /* :: */[
        Emotion.fontFamily("Tahoma, sans-serif"),
        /* [] */0
      ]
    ]);

Emotion.$$global("html, body, #app", /* :: */[
      Emotion.display(/* grid */-999565626),
      /* :: */[
        Emotion.gridTemplateRows(/* `list */[
              -944563106,
              /* :: */[
                /* `fr */[
                  22860,
                  1
                ],
                /* [] */0
              ]
            ]),
        /* :: */[
          Emotion.gridTemplateColumns(/* `list */[
                -944563106,
                /* :: */[
                  /* `fr */[
                    22860,
                    1
                  ],
                  /* [] */0
                ]
              ]),
          /* :: */[
            Emotion.gridGap(/* zero */-789508312),
            /* :: */[
              Emotion.margin(/* zero */-789508312),
              /* :: */[
                Emotion.padding(/* zero */-789508312),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

Emotion.fontFace(/* :: */[
      Emotion.fontFamily("MyFont"),
      /* :: */[
        Emotion.fontWeight(400),
        /* :: */[
          Emotion.fontStyle(/* normal */812216871),
          /* :: */[
            Emotion.src(/* :: */[
                  /* tuple */[
                    /* `url */[
                      5843823,
                      "my-font.woff"
                    ],
                    /* woff */-822282408
                  ],
                  /* :: */[
                    /* tuple */[
                      /* `url */[
                        5843823,
                        "my-font.woff2"
                      ],
                      /* woff2 */-832866854
                    ],
                    /* [] */0
                  ]
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

/*  Not a pure module */
