// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReactTemplate = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactTemplate.make, { }), "root");

/*  Not a pure module */
