// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Component = require("./Component.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var GlobalStyles = require("./GlobalStyles.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component.make(30, true, /* array */[])), "app");

/*  Not a pure module */
