// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var LayoutStyles = require("./LayoutStyles.bs.js");

var component = ReasonReact.statelessComponent("Layout");

function make(children) {
  return {
          debugName: component.debugName,
          reactClassInternal: component.reactClassInternal,
          handedOffState: component.handedOffState,
          willReceiveProps: component.willReceiveProps,
          didMount: component.didMount,
          didUpdate: component.didUpdate,
          willUnmount: component.willUnmount,
          willUpdate: component.willUpdate,
          shouldUpdate: component.shouldUpdate,
          render: (function (param) {
              return React.createElement("div", {
                          className: LayoutStyles.container
                        }, ReactDOMRe.createElementVariadic("main", {
                              className: LayoutStyles.main
                            }, children), React.createElement("footer", {
                              className: LayoutStyles.footer
                            }));
            }),
          initialState: component.initialState,
          retainedProps: component.retainedProps,
          reducer: component.reducer,
          jsElementWrapped: component.jsElementWrapped
        };
}

var Css = /* alias */0;

exports.Css = Css;
exports.component = component;
exports.make = make;
/* component Not a pure module */
