// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("@ahrefs/bs-emotion/src/Emotion.bs.js");

var container = Emotion.css(undefined, /* :: */[
      Emotion.label("container"),
      /* :: */[
        Emotion.display(/* grid */-999565626),
        /* :: */[
          Emotion.gridTemplateRows(/* `list */[
                -944563106,
                /* :: */[
                  /* `fr */[
                    22860,
                    1
                  ],
                  /* :: */[
                    /* maxContent */60557045,
                    /* [] */0
                  ]
                ]
              ]),
          /* :: */[
            Emotion.gridTemplateColumns(/* `list */[
                  -944563106,
                  /* :: */[
                    /* `fr */[
                      22860,
                      1
                    ],
                    /* [] */0
                  ]
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var main = Emotion.css(undefined, /* :: */[
      Emotion.label("main"),
      /* :: */[
        Emotion.display(/* grid */-999565626),
        /* :: */[
          Emotion.alignItems(/* center */98248149),
          /* :: */[
            Emotion.justifyItems(/* center */98248149),
            /* [] */0
          ]
        ]
      ]
    ]);

var footer = Emotion.css(undefined, /* :: */[
      Emotion.label("footer"),
      /* :: */[
        Emotion.display(/* grid */-999565626),
        /* :: */[
          Emotion.alignItems(/* center */98248149),
          /* :: */[
            Emotion.justifyItems(/* center */98248149),
            /* :: */[
              Emotion.padding(/* `px */[
                    25096,
                    20
                  ]),
              /* :: */[
                Emotion.backgroundColor(/* `hex */[
                      5194459,
                      "f7f7f7"
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

exports.container = container;
exports.main = main;
exports.footer = footer;
/* container Not a pure module */
