# Cross-platform set of build steps for building esy projects

parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      ESY__CACHE_INSTALL_PATH: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps: 
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - template: utils/restore-build-cache.yml
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      # - script: "esy test"
      #   displayName: "Test command"
      - template: utils/publish-build-cache.yml
      - bash: ./_build/default/src/analyze_example_tests/ExamplesTests.exe
      - bash: ./_build/default/util_tests/UtilTests.exe
      - bash: mkdir -p rls-release
      - bash: cp _build/default/bin/Bin.exe rls-release/reason-language-server.exe
      - task: PublishBuildArtifacts@1
        displayName: 'Upload binary'
        inputs:
            pathToPublish: 'rls-release'
            artifactName: 'rls-$(Agent.OS)'
            parallel: true
            parallelCount: 8
