// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Component1$ReactTemplate = require("./Component1.bs.js");
var Component2$ReactTemplate = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component1$ReactTemplate.make("Hello!", /* array */[])), "index1");

function make() {
  return ReasonReact.statelessComponent("hi");
}

var Awesome = /* module */[/* make */make];

var x = String(12);

var er = ReasonReact.element(undefined, undefined, ReasonReact.statelessComponent("hi"));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component2$ReactTemplate.make("", /* array */[])), "index2");

exports.Awesome = Awesome;
exports.x = x;
exports.er = er;
/*  Not a pure module */
