// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var E2e$Namewithunderscore = require("./e2e.bs.js");

var y = E2e$Namewithunderscore.x;

exports.y = y;
/* No side effect */
