// Generated by BUCKLESCRIPT VERSION 3.2.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("/Users/jared/clone/tools/reason-language-server/examples/example-react/node_modules/reason-react/src/ReactDOMRe.js");
var ReasonReact = require("/Users/jared/clone/tools/reason-language-server/examples/example-react/node_modules/reason-react/src/ReasonReact.js");
var Component1$ReactTemplate = require("./Component1.bs.js");
var Component2$ReactTemplate = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component1$ReactTemplate.make("Hello!", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component2$ReactTemplate.make("Hello!", /* array */[])), "index2");

/*  Not a pure module */
